

#define LEN_MERCHANT_PIN         4
#define LEN_MAX_REF_NUM_IN       12
#define LEN_MAX_TRACE_IN         6
#define LEN_MAX_DATE_IN          8
#define LEN_MAX_TIME_IN          6
#define LEN_WIFI_AP_LIST         20
#define LEN_MAX_SERVICE_NUM      10
#define LEN_MAX_CARDHOLDER_ITEMS 10
#define LEN_MAX_AMOUNT_LIST      13
#define LEN_MAX_AMOUNT           12
#define LEN_MIN_AMOUNT           4
#define LEN_MAX_PASSWORD         4
#define LEN_MAX_IP               12
#define LEN_MAX_SHIFT_NUM        3
#define LEN_MAX_CARD_PIN         4
#define LEN_MAX_ISO_MAC          8
#define LEN_MAX_PIN_BLOCK        8
#define LEN_MAX_BIN              6
#define LEN_MAX_PAN              19
#define LEN_MAX_TRACK2           37
#define LEN_MAX_RRN              12
#define LEN_MAX_INT_8            6
#define LEN_MAX_UINT_8           4
#define LEN_MAX_INT_16           7
#define LEN_MAX_UINT_16          6
#define LEN_MAX_INT_32           12
#define LEN_MAX_UINT_32          11
#define LEN_MAX_INT_64           21
#define LEN_MAX_UINT_64          21
#define LEN_MIN_PAYMENT_ID       6
#define LEN_MAX_PAYMENT_ID       13
#define LEN_MIN_BILL_ID          6
#define LEN_MAX_BILL_ID          13
#define LEN_MAX_STAN             6
#define LEN_MAX_PRCODE           6
#define LEN_MAX_MTI              4
#define LEN_MAX_PHONE_NUMBER     11
#define LEN_SOCKET_REC_BUFF      1024